server:
  port: 8001
  servlet:
   contextPath: /gulimall-coupon
spring:
  application:
      name: guimall-coupon
  config:
    import[0]: nacos:datasource.yml?group=dev-group
    import[1]: nacos:mybatis.yml?group=dev-group
  nacos:
    server-addr: 127.0.0.1:8848
  datasource:
    url: jdbc:mysql://192.168.0.99/gulimall_sms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: 7583d6a2-3c98-4b15-9afe-71ffbedb3c3f
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 7583d6a2-3c98-4b15-9afe-71ffbedb3c3f
      username: nacos
      password: nacos